### ISSUE TITLE
Lines diff

### ISSUE THREAD

**Issue by edgarsgogolevs** [JoshData/fast_diff_match_patch#23]
Is it possible to get difference of the lines of two strings? In default diff-match-patch python library I used `diff_linesToChars_` and `diff_charsToLines ` methods. Is there something similar I can do with this library?

**Comment by JoshData** [comment]
Better late than never?

You could implement the same strategy as DMP, which is that it splits the input into lines, assigns each unique line a character, and then performs a character diff on those lines-as-characters inputs. After the diff, each character in the output can be re-expanded to its original line.

Since it's been a year and a half and you've probably moved on :), I'm closing this issue.
